name: macOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [
          'x86_64-apple-darwin',
          'aarch64-apple-darwin'
        ]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    
    - name: Build
      run: cargo build --verbose --release --target ${{ matrix.target }}
      
    - name: Run tests
      run: cargo test --verbose --target ${{ matrix.target }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/*
        if-no-files-found: error